# GitHub Pages configuration
title: Aerial Picture Frame
description: Transform your device into the ultimate family hub with digital photo frame and smart home dashboard
url: https://timmygarrabrant.github.io/HomeDisplay
baseurl: /HomeDisplay

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .github/
  - form-handler.php
  - form-handler.js

# Include files
include:
  - _redirects

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
