# GitHub Pages configuration
title: Home Display
description: Transform your iPad into a beautiful smart home control center
url: https://yourusername.github.io/home-display-public
baseurl: /home-display-public

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .github/
  - form-handler.php
  - form-handler.js

# Include files
include:
  - _redirects

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
